# Generated by Django 5.2.8 on 2025-11-13 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('old_check_in', models.DateTimeField()),
                ('new_check_in', models.DateTimeField()),
                ('old_check_out', models.DateTimeField(blank=True, null=True)),
                ('new_check_out', models.DateTimeField(blank=True, null=True)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.checkincheckout')),
            ],
        ),
    ]
