# Generated by Django 5.2.8 on 2025-11-13 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_timeentrylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkincheckout',
            name='check_in_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
